# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get Current Time
      uses: josStorer/get-current-time@v2.0.2
      id: current-time
      with:
        format: MMDDYY
    - name: Use current time
      env:
        BUILD_VERSION: "${{ steps.current-time.outputs.formattedTime }}-${{ github.run_number }}"
      run: echo $BUILD_VERSION
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Write File
      uses: DamianReeves/write-file-action@v1.0
      with:
        # The path to the file to write
        path: ${{ env.home}}/MBBSEmu/Assets/version.txt
        # The contents of the file
        contents: $BUILD_VERSION
        # The mode of writing to use: `overwrite`, `append`, or `preserve`.
        write-mode: overwrite # optional, default is preserve
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish x86-64
      run: |
        mkdir output/win-x64
        dotnet publish MBBSEmu/MBBSEmu.csproj --output output/win-x64 --configuration Release --runtime win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:IncludeNativeLibrariesInSingleFile=true -p:PublishTrimmed=true -p:CopyOutputSymbolsToPublishDirectory=false --verbosity n
    - name: Create x86-64 Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        # Artifact name
        name: 'mbbsemu-win-x64-$BUILD_VERSION' # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: output/win-x64/*
        # The desired behavior if no files are found using the provided path.
